service: made-teams

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: eu-west-1
  memorySize: 128
  timeout: 3

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:*"
      Resource: "*"

  environment:
    DYNAMODB_TABLE: ${self:service}-${opt:stage, self:provider.stage}

custom:
  dynamodb:
    stages:
      - dev
    start:
      port: 8000
      inMemory: true
      seed: true
    seed:
      domain:
        sources:
          - table: ${self:provider.environment.DYNAMODB_TABLE}

functions:
  createUser:
    handler: handler.createUser
    events:
      - http:
          path: users/create
          method: post
  listUsers:
    handler: handler.listUsers
    events:
      - http:
          path: users/list
          method: get

resources:
  Resources:
    DynamodbTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.DYNAMODB_TABLE}
        KeySchema:
          - AttributeName: code
            KeyType: HASH
          - AttributeName: name
            KeyType: RANGE
        AttributeDefinitions:
          - AttributeName: code
            AttributeType: S
          - AttributeName: name
            AttributeType: S
        BillingMode: PAY_PER_REQUEST

plugins:
  - serverless-dynamodb-local
  - serverless-offline
