service: made-teams

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: eu-west-1
  memorySize: 128
  timeout: 3

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:*"
      Resource: "*"

  environment:
    DYNAMODB_TABLE: ${self:service}-${opt:stage, self:provider.stage}

custom:
  dynamodb:
    stages:
      - dev
    start:
      port: 8000
      inMemory: true
      seed: true
    seed:
      domain:
        sources:
          - table: ${self:provider.environment.DYNAMODB_TABLE}

functions:
  postUser:
    handler: handler.postUser
    events:
      - http:
          path: v1/users
          method: post
  putUser:
    handler: handler.putUser
    events:
      - http:
          path: v1/users/{code}
          method: put
  deleteUser:
    handler: handler.deleteUser
    events:
      - http:
          path: v1/users/{code}
          method: delete
  getUser:
    handler: handler.getUser
    events:
      - http:
          path: v1/users/{code}
          method: get
  getUsers:
    handler: handler.getUsers
    events:
      - http:
          path: v1/users
          method: get

resources:
  Resources:
    DynamodbTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.DYNAMODB_TABLE}
        KeySchema:
          - AttributeName: code
            KeyType: HASH
        AttributeDefinitions:
          - AttributeName: code
            AttributeType: S
        BillingMode: PAY_PER_REQUEST

plugins:
  - serverless-dynamodb-local
  - serverless-offline
